export MYZSHRC="$0"
export ZSH_CONFIG_DIR="$HOME/project/dotfiles/zsh"

# 独自パッチを保持しつづけるのもしんどいので
# 管理下じゃないファイル1つのデフォルトで読むようにする
source "$HOME/.zshrc_custom" 

source "$ZSH_CONFIG_DIR/zshopt.zshrc"
source "$ZSH_CONFIG_DIR/hook.zshrc"

source "$ZSH_CONFIG_DIR/env.zshrc"
source "$ZSH_CONFIG_DIR/alias.zshrc"
source "$ZSH_CONFIG_DIR/function.zshrc"

if test ! $MF_DEV
then
fi

PERLBREWRC="$HOME/perl5/perlbrew/etc/bashrc"
if test -f "$PERLBREWRC"
then
    source "$PERLBREWRC"
fi

PYTHONBREWRC="$HOME/.pythonbrew/etc/bashrc"
if test -f "$PYTHONBREWRC"
then
    source "$PYTHONBREWRC"
fi

RVMRC="/Users/yoshimi/.rvm/scripts/rvm"
if test -f "$RVMRC"
then
    source "$RVMRC"
fi
