setopt no_global_rcs

export MYZSHRC="$0"
export ZSH_CONFIG_DIR="$HOME/project/dotfiles/zsh"
export LC_ALL=ja_JP.UTF-8

source "$ZSH_CONFIG_DIR/zshopt.zshrc"
source "$ZSH_CONFIG_DIR/hook.zshrc"

source "$ZSH_CONFIG_DIR/env.zshrc"
source "$ZSH_CONFIG_DIR/alias.zshrc"
source "$ZSH_CONFIG_DIR/function.zshrc"

# 独自パッチを保持しつづけるのもしんどいので
# 管理下じゃないファイル1つのデフォルトで読むようにする
source "$HOME/.zshrc_custom"

if which rbenv > /dev/null
then
    eval "$( rbenv init - )"
fi
