export ZSH_CONFIG_DIR="$HOME/dotfiles/zsh"

# 独自パッチを保持しつづけるのもしんどいので
# 管理下じゃないファイル1つのデフォルトで読むようにする
source "$ZSH_CONFIG_DIR/custom.zshrc" 

source "$ZSH_CONFIG_DIR/zshopt.zshrc"
source "$ZSH_CONFIG_DIR/hook.zshrc"

source "$ZSH_CONFIG_DIR/env.zshrc"
source "$ZSH_CONFIG_DIR/alias.zshrc"

if test ! $MF_DEV
then
    if test ! $LOCAL_LIB_SET
    then
        export LOCAL_LIB_SET=1
        eval $(perl -I$HOME/local/lib/perl5 -Mlocal::lib=$HOME/local)
    fi
fi
