export ZSH_CONFIG_DIR="$HOME/dotfiles/zsh"

source "$ZSH_CONFIG_DIR/zshopt.zshrc"
source "$ZSH_CONFIG_DIR/hook.zshrc"

source "$ZSH_CONFIG_DIR/env.zshrc"
source "$ZSH_CONFIG_DIR/alias.zshrc"

if test ! $MF_DEV
then
    eval $(perl -I$HOME/local/lib/perl5 -Mlocal::lib=$HOME/local)
fi
